### ISSUE TITLE
ReferenceError: PersistentReactiveDict is not defined

### ISSUE THREAD

**Issue by thinkinsysdev** [RobertLowe/persistent-reactive-dict#2]
Getting the above weird error.

Added the package as described.

Then have this line in code 
mySearchResults = new PersistentReactiveDict('mySearchResults', 'temporary');

**Comment by RobertLowe** [comment]
Fixed in d9a768d999a10fd9e8a790c1bcfccece69b012c5

There was a typo in the README; 

You need to add `meteor add robertlowe:persistent-reactive-dict` not `meteor add robert-lowe:persistent-reactive-dict`.

Also, off topic: I'd advise against using `PersistentReactiveDict` for something like search results, as it's backed by local storage which can be slow. 

You can always create offline collections in Meteor: `mySearchResults = new Meteor.Collection('results', {connection: null})` for example.
